/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as OptimizerRouteImport } from './routes/optimizer'
import { Route as LogisticsRouteImport } from './routes/logistics'
import { Route as ExplainabilityRouteImport } from './routes/explainability'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSimulateRouteImport } from './routes/api.simulate'
import { Route as ApiRouteGeometryRouteImport } from './routes/api.route-geometry'
import { Route as ApiPlaceDetailRouteImport } from './routes/api.place-detail'
import { Route as ApiDataRouteImport } from './routes/api.data'
import { Route as ApiCopilotRouteImport } from './routes/api.copilot'
import { Route as ApiAutosuggestRouteImport } from './routes/api.autosuggest'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizerRoute = OptimizerRouteImport.update({
  id: '/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)
const LogisticsRoute = LogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplainabilityRoute = ExplainabilityRouteImport.update({
  id: '/explainability',
  path: '/explainability',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSimulateRoute = ApiSimulateRouteImport.update({
  id: '/api/simulate',
  path: '/api/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRouteGeometryRoute = ApiRouteGeometryRouteImport.update({
  id: '/api/route-geometry',
  path: '/api/route-geometry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaceDetailRoute = ApiPlaceDetailRouteImport.update({
  id: '/api/place-detail',
  path: '/api/place-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDataRoute = ApiDataRouteImport.update({
  id: '/api/data',
  path: '/api/data',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCopilotRoute = ApiCopilotRouteImport.update({
  id: '/api/copilot',
  path: '/api/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAutosuggestRoute = ApiAutosuggestRouteImport.update({
  id: '/api/autosuggest',
  path: '/api/autosuggest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/explainability': typeof ExplainabilityRoute
  '/logistics': typeof LogisticsRoute
  '/optimizer': typeof OptimizerRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/autosuggest': typeof ApiAutosuggestRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/data': typeof ApiDataRoute
  '/api/place-detail': typeof ApiPlaceDetailRoute
  '/api/route-geometry': typeof ApiRouteGeometryRoute
  '/api/simulate': typeof ApiSimulateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/explainability': typeof ExplainabilityRoute
  '/logistics': typeof LogisticsRoute
  '/optimizer': typeof OptimizerRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/autosuggest': typeof ApiAutosuggestRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/data': typeof ApiDataRoute
  '/api/place-detail': typeof ApiPlaceDetailRoute
  '/api/route-geometry': typeof ApiRouteGeometryRoute
  '/api/simulate': typeof ApiSimulateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copilot': typeof CopilotRoute
  '/explainability': typeof ExplainabilityRoute
  '/logistics': typeof LogisticsRoute
  '/optimizer': typeof OptimizerRoute
  '/predictions': typeof PredictionsRoute
  '/reports': typeof ReportsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/autosuggest': typeof ApiAutosuggestRoute
  '/api/copilot': typeof ApiCopilotRoute
  '/api/data': typeof ApiDataRoute
  '/api/place-detail': typeof ApiPlaceDetailRoute
  '/api/route-geometry': typeof ApiRouteGeometryRoute
  '/api/simulate': typeof ApiSimulateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/copilot'
    | '/explainability'
    | '/logistics'
    | '/optimizer'
    | '/predictions'
    | '/reports'
    | '/sitemap.xml'
    | '/api/autosuggest'
    | '/api/copilot'
    | '/api/data'
    | '/api/place-detail'
    | '/api/route-geometry'
    | '/api/simulate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/copilot'
    | '/explainability'
    | '/logistics'
    | '/optimizer'
    | '/predictions'
    | '/reports'
    | '/sitemap.xml'
    | '/api/autosuggest'
    | '/api/copilot'
    | '/api/data'
    | '/api/place-detail'
    | '/api/route-geometry'
    | '/api/simulate'
  id:
    | '__root__'
    | '/'
    | '/copilot'
    | '/explainability'
    | '/logistics'
    | '/optimizer'
    | '/predictions'
    | '/reports'
    | '/sitemap.xml'
    | '/api/autosuggest'
    | '/api/copilot'
    | '/api/data'
    | '/api/place-detail'
    | '/api/route-geometry'
    | '/api/simulate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopilotRoute: typeof CopilotRoute
  ExplainabilityRoute: typeof ExplainabilityRoute
  LogisticsRoute: typeof LogisticsRoute
  OptimizerRoute: typeof OptimizerRoute
  PredictionsRoute: typeof PredictionsRoute
  ReportsRoute: typeof ReportsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiAutosuggestRoute: typeof ApiAutosuggestRoute
  ApiCopilotRoute: typeof ApiCopilotRoute
  ApiDataRoute: typeof ApiDataRoute
  ApiPlaceDetailRoute: typeof ApiPlaceDetailRoute
  ApiRouteGeometryRoute: typeof ApiRouteGeometryRoute
  ApiSimulateRoute: typeof ApiSimulateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimizer': {
      id: '/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof OptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logistics': {
      id: '/logistics'
      path: '/logistics'
      fullPath: '/logistics'
      preLoaderRoute: typeof LogisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explainability': {
      id: '/explainability'
      path: '/explainability'
      fullPath: '/explainability'
      preLoaderRoute: typeof ExplainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/simulate': {
      id: '/api/simulate'
      path: '/api/simulate'
      fullPath: '/api/simulate'
      preLoaderRoute: typeof ApiSimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/route-geometry': {
      id: '/api/route-geometry'
      path: '/api/route-geometry'
      fullPath: '/api/route-geometry'
      preLoaderRoute: typeof ApiRouteGeometryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/place-detail': {
      id: '/api/place-detail'
      path: '/api/place-detail'
      fullPath: '/api/place-detail'
      preLoaderRoute: typeof ApiPlaceDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/data': {
      id: '/api/data'
      path: '/api/data'
      fullPath: '/api/data'
      preLoaderRoute: typeof ApiDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/copilot': {
      id: '/api/copilot'
      path: '/api/copilot'
      fullPath: '/api/copilot'
      preLoaderRoute: typeof ApiCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/autosuggest': {
      id: '/api/autosuggest'
      path: '/api/autosuggest'
      fullPath: '/api/autosuggest'
      preLoaderRoute: typeof ApiAutosuggestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopilotRoute: CopilotRoute,
  ExplainabilityRoute: ExplainabilityRoute,
  LogisticsRoute: LogisticsRoute,
  OptimizerRoute: OptimizerRoute,
  PredictionsRoute: PredictionsRoute,
  ReportsRoute: ReportsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiAutosuggestRoute: ApiAutosuggestRoute,
  ApiCopilotRoute: ApiCopilotRoute,
  ApiDataRoute: ApiDataRoute,
  ApiPlaceDetailRoute: ApiPlaceDetailRoute,
  ApiRouteGeometryRoute: ApiRouteGeometryRoute,
  ApiSimulateRoute: ApiSimulateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
